apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubeweekly-jobs
spec:
  schedule: "*/12 * * * 3"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubeweekly
            image: kubeweekly:latest
            args:
            - npm run trigger
          restartPolicy: OnFailure