apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubeweekly-jobs
  namespace: default
spec:
  schedule: "* 6 * * 6" # will update the yaml file every saturday at 6:00 am 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubeweekly
            image: cloudnativeid/kubeweekly:latest
            args:
            - npm run trigger
          restartPolicy: OnFailure
