apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubeweekly-jobs
  namespace: default
spec:
  schedule: "0 12 * * *" # will update the kubeweekly repository yaml At 09:00 everyday
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubeweekly
            image: cloudnativeid/kubeweekly:1.0.0
            args:
            - npm run trigger
          restartPolicy: OnFailure
